spring:
  application:
    name: config-clinet
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
    config:
      discovery:
        service-id: config-server
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka