eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8991
spring:
  application:
    name: gate-way
  cloud:
    gateway:
      routes:
#      - id: cookie_route
#        uri: http://httpbin.org
#        predicates:
#        - Cookie: chocolate, ch.p
#      - id: method_route
#        uri: lb://service-feign
#        predicates:
#        - Method=GET
#        配置文件方式转发
      - id: myRoute
#        lb表示通过注册中心获取
        uri: lb://service-feign
        predicates:
        - Path=/a/**
        filters:
        - StripPrefix=1
#        全局断路器
      default-filters:
      - name: Hystrix
        args:
          name: fallbackcmd
          fallbackUri: forward:/fallback