eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8000}/eureka/


server:
  port: 7070
  servlet:
    context-path: /authserver

# Our certificate settings for enabling JWT tokens
jwt:
  certificate:
    store:
      file: classpath:/certificate/mykeystore.jks
      password: abirkhan04
    key:
      alias: myauthkey
      password: abirkhan04
